### ISSUE TITLE
 C# / .Net samples

### ISSUE THREAD

**Issue by peckjon** [algorithmiaio/dev-center#101]
Our current recommendation for C# / .Net devs is to use the cURL client, but I don't think we have any code samples for them?  We should add something along these lines (untested) for them:

```
using (var client = new HttpClient()) { 
    client.BaseAddress = new Uri(@"https://api.algorithmia.com/v1/algo/demo/Hello"); 
    client.DefaultRequestHeaders.Accept.Clear(); 
    client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json")); 
    client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Simple","YOR_API_KEY"); 
    HttpResponseMessage response = await client.PostAsync("", new StringContent(data)); 
    return await response.Content.ReadAsStringAsync();
}
```

**Comment by StephanieKim** [comment]
We have a C# client coming next - lets get an ETA on this before adding these samples for C#, but good idea for ones we are never going to implement (or at least not anytime soon).

**Comment by peckjon** [comment]
Confirmed w/ Kenny that C* client won't be for at least another Q.  Proceeding with sample.

**Comment by peckjon** [comment]
Closed via https://github.com/algorithmiaio/dev-center/commit/23a39ce127620c01fc3087185b056227cb47266e
