### ISSUE TITLE
Make Getting Started Page Interactive

### ISSUE THREAD

**Issue by StephanieKim** [algorithmiaio/dev-center#103]
Originally we wanted this to be similar to how algorithm description pages code examples work in the "Use Algorithm" code sample section
<img width="1069" alt="screen shot 2017-02-17 at 10 53 07 am" src="https://cloud.githubusercontent.com/assets/1320334/23078892/56f89cf0-f4ff-11e6-8b53-5123ffe21f29.png">

We should come up with something similar or at the very least make the code examples we have in a tab format and make them pretty.

**Comment by peckjon** [comment]
Current embedding template is in Scala.  Although devcenter content is embedded in the main (Scala) website, the embedding is uninterpreted, so we can't use the template directly.  Alternatives:

- scrape the template output, reinterpret in Ruby/JS to embed current user key etc (brittle, violates DRY)
- rewrite entirely in an AngularJS or other frontend-only directive/inclusion (time-costly)
- use an iFrame (oh how very 90s, but could be made to look good)
- have a "try it" link which leads to https://algorithmia.com/algorithms/some/algo#language
- have a "try it" link which fires a popover
- ?

**Comment by peckjon** [comment]
Decision: use Angular directive for code samples as found on new homepage
