### ISSUE TITLE
Document tmpfile pattern

### ISSUE THREAD

**Issue by peckjon** [algorithmiaio/dev-center#106]
Not sure if this should go in devcenter or API docs (or both), but there doesn't seem to be documentation for the save-to-URI pattern when writing an Algo:

```
tempfile = "/tmp/"+uuid.uuid4()+".tmp"
save_some_output_to(tempfile)
client.file(file_uri).putFile(tempfile)
```

- [x] Java
- [x] JS
- [x] Python
- [x] R
- [x] Ruby
- [x] Rust
- [x] Scala

**Comment by StephanieKim** [comment]
For creating an algorithm? No that's never had documentation AFAIK - good catch! It should only go into algorithm developer guides
