### ISSUE TITLE
Getting Started Hello World uses Incorrect Version

### ISSUE THREAD

**Issue by anaimi** [algorithmiaio/dev-center#121]
When deploying CODEX, a demo/HelloWorld/0.1.0 is created. 

The Getting Started page gives an example for demo/HelloWorld/0.1.1 which doesn't exist. This breaks the first impression for CODEX customer.

**Comment by jamesatha** [comment]
Where in the docs do we say that? Let's just update it to use latest (without specifying a version)

**Comment by jamesatha** [comment]
That has been updated
