### ISSUE TITLE
80 slot limits shouldn't be documented in each client

### ISSUE THREAD

**Issue by jamesatha** [algorithmiaio/dev-center#127]
Some of the clients have this info. Some of them don't. I think this shouldn't be in the clients and should be documented somewhere else

**Comment by peckjon** [comment]
@jamesatha  Literally just added this to devctr via https://github.com/algorithmiaio/dev-center/issues/118 -- I've had enough people ask on Intercom that it seemed worth adding.

Are you saying it is in the actual individual Clients, not just the docs?

**Comment by StephanieKim** [comment]
Yeah this seems like it should go in the API docs - Anthony made a table with support for each client - if we changed it up a bit we might be able to squeeze it in there http://docs.algorithmia.com/#clients

**Comment by peckjon** [comment]
Standardized (added to all except Alexa and CLI)
