### ISSUE TITLE
page loads with all options on left nav bar expanded

### ISSUE THREAD

**Issue by doppenhe** [algorithmiaio/dev-center#143]
<img width="249" alt="screen shot 2017-11-15 at 9 12 34 am" src="https://user-images.githubusercontent.com/2166701/32840266-27bb6074-c9e5-11e7-91fe-7ba15a81c690.png">

**Comment by JamesHoover** [comment]
FYI the dev center updates were not pushed to test

**Comment by anowell** [comment]
For future reference, we could get the dev-center to deploy to 2 separate buckets, master vs prod branches, and have rest and prod use the respective buckets. Not gonna happen today, but if we anticipate wanting dev-center in test to be different than prod more often, we should make that happen.
