### ISSUE TITLE
Tensorflow updates

### ISSUE THREAD

**Issue by StephanieKim** [algorithmiaio/dev-center#145]
There have been changes to TF that should be shown in the guides (like instead of a single ckpt file there are two. Should also show the protobuf (.meta) file that you need. Probably should redo the saved model and go through the tutorial and update.

**Comment by gilbeckers** [comment]
is tensorflow-gpu v1.3.0 fully supported?

**Comment by StephanieKim** [comment]
Sorry if we didn't get back to you @gilbeckers but you might have been the person working with my coworker who created the 1.3.0 wheel: https://algorithmia.com/developers/algorithm-development/model-guides/tensorflow/ if you scroll down under "set your dependencies" modal there is a message about the wheels.
