### ISSUE TITLE
Add file method description in client guides.

### ISSUE THREAD

**Issue by StephanieKim** [algorithmiaio/dev-center#146]
From user:
"yeah from the python client guide (https://algorithmia.com/developers/clients/python/) it wasn't clear to me that client.file(imgpath).getFile().name gives you the temp path of the file on the server. Only after the examination of source code of some other open source projects it became clear"

So add info about file methods used in client guides (currently they are all in api docs), and make clear what the methods return in ALL langs

**Comment by peckjon** [comment]
Also:
- note how to get a remote file into local filesystem (common use-case for colorizer etc)
- note that Hosted Data cannot be served thru GET, and suggest alternatives (S3)

**Comment by peckjon** [comment]
- [x ] python
- [ ] go
- [ ] java
- [ ] javascript
- [ ] c#
- [ ] node
- [ ] r
- [ ] ruby
- [ ] rust
- [ ] scala
- [ ] android
