### ISSUE TITLE
Images missing in CNTK Hosting Guide

### ISSUE THREAD

**Issue by besirkurtulmus** [algorithmiaio/dev-center#152]
The [CNTK guide](https://algorithmia.com/developers/algorithm-development/model-guides/cntk/) seems to be missing 2 images.

The [data collection](https://algorithmia.com/developers/images/post_images/model_hosting/cntk_data_collection.png) and [dependencies](https://algorithmia.com/developers/images/post_images/model_hosting/cntk_dependencies.png) images are missing.

**Comment by zeryx** [comment]
gah, I'll get on this when I refactor the CNTK docs this week

**Comment by zeryx** [comment]
CNTK is not supported currently, finally got around to looking at this and I removed cntk from our doc page.
