### ISSUE TITLE
Explain how to import when you're working with folders

### ISSUE THREAD

**Issue by StephanieKim** [algorithmiaio/dev-center#156]
from src.folder.file 
instead of:
from folder.file 

Related to:
```
from folder.file import something
```
It throws the error:
"ImportError: No module named folder.file"

To be more clear: Python3 users will need to use:
from .somefile import *

**Comment by jamesatha** [comment]
Just an fyi: the syntax is different for python 2 and 3

**Comment by StephanieKim** [comment]
Jon told me that this is the right syntax:
from .somefile import *
-using a leading dot which is how he got it to work for a user.

@jamesatha I believe the above is for Python3, what is the syntax for Python2?
