### ISSUE TITLE
Change featured blog posts 

### ISSUE THREAD

**Issue by StephanieKim** [algorithmiaio/dev-center#158]
Featured blog posts at bottom of dev center are old: https://algorithmia.com/developers/ set a cycle of updating them regularly

**Comment by JamesHoover** [comment]
+1 for this. im sure we could automatically pull the latest 3...that was the original idea at least

**Comment by StephanieKim** [comment]
@JamesHoover Yeah, not sure how it's coded right now but that would be awesome if we could pull down from blog.

**Comment by peckjon** [comment]
That’d be pretty easy — WP provides an RSS feed
