### ISSUE TITLE
Python runlocal should mention setting LANGUAGE_VERSION

### ISSUE THREAD

**Issue by anowell** [algorithmiaio/dev-center#168]
Any mention of `algo runlocal` for python algos needs to mention that you need to first set the environment variable `LANGUAGE_VERSION=python3` (or `python2`) for it to work.

**Comment by peckjon** [comment]
Thanks @anowell  !  Moved this to https://algorithmia.atlassian.net/browse/DC-39

If you're aware of any specific locations, could you mention on DC-39?  Otherwise we'll just search; should be obvious.
