### ISSUE TITLE
AlgoDev language guides page renders poorly on Firefox

### ISSUE THREAD

**Issue by anowell** [algorithmiaio/dev-center#24]
http://developers.algorithmia.com/algorithm-development/client-guides/

![screen shot 2016-10-19 at 13 35 48-fullpage](https://cloud.githubusercontent.com/assets/2629687/19534658/e8a7545a-9601-11e6-9d28-3e66c2d87091.png)

**Comment by Argoday** [comment]
Note: renders extra poorly in mobile (overlapping text)

**Comment by StephanieKim** [comment]
This should be reviewed again with new design before release

**Comment by anowell** [comment]
I'm happy to close this. The redesign, looks fine for me in FF, and the text no longer updates (at least down to 320px wide).
