### ISSUE TITLE
R docs show incorrect way of setting options

### ISSUE THREAD

**Issue by doppenhe** [algorithmiaio/dev-center#27]
Url:http://docs.algorithmia.com/?r#query-parameters

**Expected:**
algo <- client$algo('util/echo')
algo$set_options(timeout=60, stdout=FALSE)

**Actual:**
algo <- client$algo('util/echo')$set_options(timeout=60, stdout=FALSE)
result <- algo$pipe('HAL 9000')$result

**Comment by jamesatha** [comment]
Ya, this is not a chaining method so the documentation is wrong.
Also, it's camelcased, so it should be setOptions. I'll fix that

**Comment by StephanieKim** [comment]
oops don't know where I got that from since it's in your docs James - are you committing now?
