### ISSUE TITLE
[python client guide]: lets provide the sample .txt file

### ISSUE THREAD

**Issue by doppenhe** [algorithmiaio/dev-center#35]
http://developers.algorithmia.com/application-development/client-guides/python/

![screenshot 2016-12-20 17 08 05](https://cloud.githubusercontent.com/assets/2166701/21373864/e5c07df6-c6d6-11e6-8d09-273b0563621e.png)

**Comment by StephanieKim** [comment]
Created folder called data_assets and put text file for client guides. Saved users an extra click from getting it on the wiki. Will show on next build
