### ISSUE TITLE
[python client guide] might be worth explaining what ReadAcl, AclType are

### ISSUE THREAD

**Issue by doppenhe** [algorithmiaio/dev-center#36]
http://developers.algorithmia.com/application-development/client-guides/python/

![screenshot 2016-12-20 17 09 02](https://cloud.githubusercontent.com/assets/2166701/21373882/158f1fec-c6d7-11e6-9936-a175545260fe.png)

**Comment by StephanieKim** [comment]
These are explained in the guide under Work with Directory Permissions heading, and guide does describe at the imports why you are importing those. Closing ticket.
