### ISSUE TITLE
Anchors for Table of Contents should not be displayed as links

### ISSUE THREAD

**Issue by JamesHoover** [algorithmiaio/dev-center#41]
In markdown the anchor headers for the table of contents should be styled with a header then an 'a' tag with the ID as the name attribute.

Old
`## [Available Libraries](#available-libraries)`

New
`## Available Libraries<a name="available-libraries"></a>`

**Comment by StephanieKim** [comment]
@JamesHoover All but the first one looks like this (and I changed the first one to an anchor):
So table of contents: 
* [Create an Algorithm](#create-algorithm)

Then header:
## <a id="create-algorithm">Create an Algorithm</a>

So besides the first one changing to an anchor was there anything else I needed to do? As in I'm not sure if you want me to add the "name" attribute as well.

Thanks :-)

**Comment by JamesHoover** [comment]
As long as jumping works and the headers are not purple (appearing as links), im happy

**Comment by StephanieKim** [comment]
K done :-)
