### ISSUE TITLE
Autofocus for search bar

### ISSUE THREAD

**Issue by besirkurtulmus** [algorithmiaio/dev-center#45]
When you go to the search page, having auto-focuse on the search bar would be a better experience.

![screen shot 2017-01-24 at 10 58 07 am](https://cloud.githubusercontent.com/assets/5170389/22262012/052652de-e224-11e6-9a2c-ed6b5d8423d7.png)

**Comment by anowell** [comment]
Is a bit less relevant in the new devcenter, but I did set focus on the search if you landed directly on a search page, so I think this is good to close.
