### ISSUE TITLE
Meta Images Are Broken / Wrong Sizes

### ISSUE THREAD

**Issue by mkiser** [algorithmiaio/dev-center#48]
Both the twitter and fb images 404. I presume it's because the path doesn't exist, yet. 

The correct size for each of these should be: 

**Twitter** 240px by 240px / less than 1MB

**FB** 400px by 400px 

In both cases, let's use the Algorithmia bin tree logo on a white background. 

`<meta name="twitter:image" content="https://algorithmia.com/developers/images/logos/AlgorithmiaLogo120x120.png">
`
`<meta property="og:image" content="https://algorithmia.com/developers/images/logos/AlgorithmiaLogo.png">
`

**Comment by anowell** [comment]
yeah, the 404 is just specific to not being in prod yet. I think an already planned deploy will fix that shortly. That said, we're using the images used by the current devcenter, and I don't think the match the specific logo or sizes you have in mind here:

`twitter:image`: https://test.algorithmia.com/developers/images/logos/AlgorithmiaLogo120x120.png
`og:image`: https://test.algorithmia.com/developers/images/logos/AlgorithmiaLogo.png

@JamesHoover wanna find the right images and sizes to use here? These are just set [here in _config.yml](https://github.com/algorithmiaio/dev-center/blob/one_algorithmia/_config.yml#L5-L6)

**Comment by mkiser** [comment]
Cool. Sizes listed are the desired size for retina display.

**Comment by StephanieKim** [comment]
@mkiser want to confirm this is done? I don't know where they are supposed to exist on the page and I don't see them anywhere on: https://test.algorithmia.com/developers
