### ISSUE TITLE
Double-check canonicals are being set

### ISSUE THREAD

**Issue by mkiser** [algorithmiaio/dev-center#50]
Not sure if this is a test environment bug or something we need to fix:

The canonical URLs are currently missing the /developers/ part of the path. 

Current:
`    <link rel="canonical" href="https://algorithmia.com/client-guides/javascript/">
`
Should be
`    <link rel="canonical" href="https://algorithmia.com/developers/client-guides/javascript/">
`

**Comment by anowell** [comment]
fixed.
