### ISSUE TITLE
H1 tag

### ISSUE THREAD

**Issue by mkiser** [algorithmiaio/dev-center#51]
Looks like we put the H1 tag around the generic "Developer Center" header throughout the site. 

The preferred approach would be to put the H1 tag around a header that better describes the page. 

For instance: 

**Current H1 tag**
`<h1>Developer Center</h1>
`

**Preferred H1 tag location**
```
<h1 class="whitespace-sm">
<img src="/developers/images//language_logos/js.svg" alt="" itemprop="image" class="title-icon">
Javascript</h1>
```

**Comment by JamesHoover** [comment]
There _should_ be only one h2 per page (outside of the imported blog content). I can replace those with h1s and make sure the font size doesn't change. Then would you want to remove the h1 tag from `Developer Center`?

**Comment by mkiser** [comment]
We only want one H1 on the page and it should be around the specific content header (i.e. Javascript). We can wrap the H2 around the Developer Center. 

I assume you'll need to do some CSS class wizardry to ensure the fonts and sizes remain correct/as-is.

* note, i had the code in the above example wrong. it previously showed H2 tag; was suppose to be a H1 tag.
