### ISSUE TITLE
Client Guides Missing?

### ISSUE THREAD

**Issue by mkiser** [algorithmiaio/dev-center#54]
Not sure if this is on purpose, but I came across a few client guides that tell users to go to Github for the guide. This feels like a missed opportunity to help devs get started faster. 

<img width="1159" alt="screen shot 2017-01-25 at 1 56 48 pm" src="https://cloud.githubusercontent.com/assets/2197111/22311011/56b5b8d2-e306-11e6-9c59-13c60e91e091.png">

The dev center is suppose to be the one place with the collected knowledge for getting started with Algorithmia. Shipping users off to Github shows a lack of respect for our user.

I look at what Firebase does with their dev center. They have this great guide for getting started with the Firebase Tool (CLI):
https://firebase.google.com/docs/cli/

But they also have this Github repo:
https://github.com/firebase/firebase-tools

The former is the comprehensive getting started guide. The latter is the repo with the client and a stripped down list of reference commands. Both are helpful, but for different reasons: the former is for the n00bs, the latter is for the person already familiar.

**Comment by anowell** [comment]
all the client guides are missing. the versions generated from github READMEs were ripped out given that steph just rewrote them all. They just haven't been merged into the `one_algorithmia` branch yet.

**Comment by anowell** [comment]
clarification: all the client guides **that were previously generated from github READMEs** are missing

**Comment by mkiser** [comment]
ahhh, got it. but they'll be there once merged in?

**Comment by anowell** [comment]
correct.

**Comment by anowell** [comment]
I went ahead and merged them in.. (I might regret this if I end up battling a bunch of 3-branch merge conflicts later)... the revamped client guides are now published to test.
