### ISSUE TITLE
Some client guides use .my instead of your_username in examples 

### ISSUE THREAD

**Issue by StephanieKim** [algorithmiaio/dev-center#55]
These should be all set to your_username

**Comment by anowell** [comment]
actually, if we're not using `.my`, all of these should be set to `@username` for the new devcenter. The embedding process will replace that with their username if signed in. You can also now use `@apiKey` in your guides. :-D

**Comment by StephanieKim** [comment]
That's super cool - I can add those to the docs before we flip it over

**Comment by StephanieKim** [comment]
@anowell So working on this now. For go using your @apiKey would just be: var apiKey = "{@apiKey}" correct?

**Comment by anowell** [comment]
turns out I was wrong. the Play/Twirl interpolation didn't quite apply like I thought, and rather than make it work, Play now just does a `replaceAll` for `YOUR_USERNAME` and `YOUR_API_KEY` from the devcenter.

**Comment by StephanieKim** [comment]
DOne with https://github.com/algorithmiaio/dev-center/commit/e5b4d89a6faa65c6a0eb6477fcfbe126ee119a36
