### ISSUE TITLE
There used to be info sections that were highlighted using jekyll {: .notice-info} 

### ISSUE THREAD

**Issue by StephanieKim** [algorithmiaio/dev-center#56]
For instance this section on the guides:

Instead of your username you can use ‘.my’ when calling algorithms. For more information about the ‘.my’ pseudonym check out the Hosted Data Guide. 

used to be highlighted using jekyll {: .notice-info} while others used: {: .notice-warning}

If they aren't available to use anymore than minimum should be **Note:** or **Warning:**

**Comment by anowell** [comment]
likely a side-effect of ripping out all the jekyll specific CSS and not creating an equivalent in the new world. I'll see if I can hack these to just use the [bootstrap alert style](http://getbootstrap.com/components/#alerts) used elsewhere, unless @JamesHoover has something else in mind.

**Comment by StephanieKim** [comment]
Not gonna lie - they were super ugly but helpful

**Comment by JamesHoover** [comment]
I would rather make new ones than use the bootstrap style

**Comment by anowell** [comment]
cool. should think about how they might fit in elsewhere in the site. we do use the bootstrap alerts elsewhere, so do keep in mind how we might unify such styles:

```
$ rg alert-success | wc -l
8
$ rg alert-warning | wc -l
15
$ rg alert-info | wc -l   
8
$ rg alert-danger | wc -l
9
```

**Comment by JamesHoover** [comment]
The plan was to just update the dev center ones and later make the rest of the site to be consistent

**Comment by JamesHoover** [comment]
fixed on the algorithmia repo
