### ISSUE TITLE
Client guides missing .txt data file for working through the guides

### ISSUE THREAD

**Issue by StephanieKim** [algorithmiaio/dev-center#57]
/data_assets/burning_daylight.txt is missing and if we aren't going to host this file for users to use than we need to remove that link and reference. The reason why this is not simply hosted by https://algorithmia.com/data/hosted is that in the guide we use their local copy of the file to show how to upload a local file to hosted data.

Note: there is still the link to wikimedia which is where I copied and pasted it from so users can still do that easily.

**Comment by peckjon** [comment]
Public domain data, small file.  Suggest we host.  Not that wikipedia is gonna die soon, but it changes.

**Comment by peckjon** [comment]
Fixed by https://github.com/algorithmiaio/dev-center/issues/73 as far as I can tell
