### ISSUE TITLE
Some of the screenshots look huge

### ISSUE THREAD

**Issue by StephanieKim** [algorithmiaio/dev-center#58]
On new site the Working with Data guides' screenshots look ginormous. Maybe scale these down a bit? https://test.algorithmia.com/developers/data/dropbox/

**Comment by JamesHoover** [comment]
How would you like to go about a fix? I can make classes to place on images case by case to limit the size. I can limit the overall size so no image goes past x size. Or we can shrink the natural size of the images.

**Comment by anowell** [comment]
We can scale down images if they are particularly large, but should still keep sizes that are still crisp on high DPI displays. I think images should default to `max-width: 100%` of the content area. In some cases (e.g. showing off a major part of a page) a wider screenshot is a good solution (so they still fill 100% width without scaling up), and in other cases (e.g. dialogs), we should probably set `width: ??px` as needed.

(I think that is the right mix of width and max-width, but I could be mistaken.)

![](http://www.tivix.com/uploads/images/css_is_awesome.height-312.png)

**Comment by peckjon** [comment]
Any reason not to have something like `.contained-image {max-width: 800px;}` ?

**Comment by JamesHoover** [comment]
Im thinking that if we did the `.max-width-800` then we might as well just reduce the img size and reduce bandwidth

**Comment by peckjon** [comment]
Retina screens, tho...

**Comment by mkiser** [comment]
That's the window resolution for users on desktop, plan accordingly: 

1366x768 (23%)
1920x1080 (17%)
1440x900 (10%)

Other stuff to help you make a decision:
75% Desktop

Browser
62% Chrome
18% Safari
11% Firefox

OS
43% Windows
23% Macintosh 
15% iOS

**Comment by anowell** [comment]
Mapping back to bootstrap breakpoints, the devcenter's content container falls into one of these widths:
- lg: 850px
- md: 700px
- sm: 535px
- xs: full device width minus padding caps this at 740px but more likely 300-400px depending on device (e.g. 355px for an iPhone 6s)

**Comment by JamesHoover** [comment]
So given that, I can make `lg, md, sm` classes (`xs` aka full width would be default) that can be added to the img to limit its maximum width

**Comment by anowell** [comment]
that's why i suggested `max-width: 100%` (which might already be the default, not sure).. that should contain the image within the container as it does already regardless of viewport...

the question is how to shrink the things that you don't want to take up 100% of the content container width. And my hunch is, if you know an image looks bad above 400px wide, just set that to `width: 400px`. But trying to do CSS off the top of my head never really works in practice...

**Comment by JamesHoover** [comment]
`max-width: 100%` is the default right now. I think we are on the same page here. using CSS to limit the max width and never go over 100% of the container.

**Comment by JamesHoover** [comment]
OK i added rules to limit the width of screenshots. 

You can add these classes directly to the img:
`img-lg` width: 850px
`img-md` width: 700px
`img-sm` width: 535px

Let me know if you need another size.

**Comment by StephanieKim** [comment]
Added classes as needed - on prod
