### ISSUE TITLE
nodejs api spec missing first line: require algorithmia

### ISSUE THREAD

**Issue by doppenhe** [algorithmiaio/dev-center#6]
![screenshot 2016-03-08 18 07 51](https://cloud.githubusercontent.com/assets/2166701/13623120/09297e10-e559-11e5-8833-c95dd89a8d0e.png)
![screenshot 2016-03-08 18 09 02](https://cloud.githubusercontent.com/assets/2166701/13623125/0de40b6e-e559-11e5-8209-f8a940ad5c45.png)

**Comment by lizrush** [comment]
Added to api-docs: https://github.com/algorithmiaio/api-docs/commit/f27e89ff8b5025897ce9a61cf9de33ba95f4d63e
