### ISSUE TITLE
Float the top navbar-header

### ISSUE THREAD

**Issue by peckjon** [algorithmiaio/dev-center#60]
On desktops, it is useful to have the navbar-header within easy reach, especially given the height of our banner.  I'd suggest floating (absolute-pos) that element for non-mobile resolutions.

**Comment by mkiser** [comment]
Agreed, but let's address this as a site-wide issue when start iterating on those elements vs as a one-off dev center thing.

**Comment by anowell** [comment]
This sounds like a webserver design request (independent of the devcenter).

**Comment by peckjon** [comment]
Yes to both.  Where to re-shelve this?

**Comment by anowell** [comment]
@peckjon - how about moving it to the algorithmia repo. You could move it to Asana, but I think it'd fall too low on priorities, where as a Github issue, it's more likely to get fixed during one of our occasional pushes to cleanup low-hanging bugs.

**Comment by peckjon** [comment]
Moved to https://github.com/algorithmiaio/algorithmia/issues/858
