### ISSUE TITLE
Rewrite algorithm development guides

### ISSUE THREAD

**Issue by StephanieKim** [algorithmiaio/dev-center#62]
#14 http://developers.algorithmia.com/algorithm-development/client-guides/
These guides are to be updated based on the Python guide

**Comment by StephanieKim** [comment]
Perhaps optional to do these post launch

**Comment by peckjon** [comment]
Yes, and shall we divvy and calendar them during the content meeting?

**Comment by StephanieKim** [comment]
Started R guide & updated a bit of the Python. Between other workloads rough estimate is 2 days for each guide.

**Comment by peckjon** [comment]
@peckjon will do: JavaSCript, Ruby, Rust

**Comment by peckjon** [comment]
Note: path has changed to https://test.algorithmia.com/developers/algorithm-development/languages/

**Comment by StephanieKim** [comment]
Python is updated to use as template and R is done

**Comment by StephanieKim** [comment]
Steph working on Scala & Java (Python and R done) - note: keep JSON info for Scala and Java and add small snippet about us using rjson for R docs.

**Comment by StephanieKim** [comment]
@peckjon so for the Rust guide some sections you'll want to keep that are not in the Python and R guides such as JSON parsing. If you have any questions about other sections that might need to stay in you can ask @anowell :-)

**Comment by StephanieKim** [comment]
Closing out this ticket and creating a separate one for Scala which won't be done until the Scala client and client guide is done.
