### ISSUE TITLE
Update and enhance permissions and versioning page 

### ISSUE THREAD

**Issue by StephanieKim** [algorithmiaio/dev-center#67]
Right now this is based off of: http://developers.algorithmia.com/basics/algorithm_basics/ and now at: https://test.algorithmia.com/developers/basics/
 
Jon has some ideas about how to make the "Versioning" section better as well.

Pricing page stays the same for now because on homepage pricing page will change and be the main hub for all pricing info.

**Comment by peckjon** [comment]
Many of those ideas had to do with the actual algorithm-developer interface... adding versioning comments, adding a `/beta` psuedo-version, etc.

But as to this page: IMO we should emphasize in the *first* paragraph that app devs should version-lock?  The only real warning about this isn't until the last sentence of the page.

**Comment by peckjon** [comment]
I did have some thoughts about describing the Algorithm Editor interface more fully, with regard to versioning (things like, if you hit Publish before Compile, it deploys the last-compiled version, not the one you see on the screen)... but that belongs on a more focused page.  We don't have one detailing the editor yet, do we?

**Comment by peckjon** [comment]
Closed with https://github.com/algorithmiaio/dev-center/commit/58e0d842f9f172bb1139cfd38656851fa85ca09c and https://github.com/algorithmiaio/dev-center/commit/5462768f5ae1bb84a361df86c99603e04757715f
