### ISSUE TITLE
Understanding Your Profile page is missing

### ISSUE THREAD

**Issue by StephanieKim** [algorithmiaio/dev-center#68]
http://developers.algorithmia.com/basics/your-profile/ should be under https://test.algorithmia.com/developers/faqs/ 

I'm open to other places where it could go but going off what we decided in this doc: https://docs.google.com/document/d/10Wb81wvePhn_D7U1Gw5VSjxglygjYQeaqqWEuktE2hM/edit

**Comment by StephanieKim** [comment]
It's in the wrong spot and not linked to anywhere: /devcenter/basics/

**Comment by anowell** [comment]
pro-tip, you can find these "missing" pages with the devcenter search.. (e.g. search for "profile")

**Comment by peckjon** [comment]
Hrm, almost feel like this should be top-level, since it applies both to App Devs and Algo Devs...

**Comment by StephanieKim** [comment]
@peckjon it was supposed to go under https://test.algorithmia.com/developers/faqs/ as it's own page. where are you thinking instead?

**Comment by StephanieKim** [comment]
What do you guys think of adding a /basic in nav and keeping these three under it which is similar to how it was in old dev center. Not sure why they were all slated to go under FAQ 
algorithm_profiles/	
customizing-api-keys/	
organization_profiles/

**Comment by peckjon** [comment]
Yes. I feel there are several pages here which would neatly fall and that section, and will get lost otherwise.

**Comment by mkiser** [comment]
This is the up-to-date information architecture doc:
https://docs.google.com/spreadsheets/d/1ysJJ0hOC6mx3xUGwU37HbwtWdt6SmqcZFUJS19QDOu8/edit#gid=0

Just make everything fit within in the framework

**Comment by StephanieKim** [comment]
K so all we need to do then is create the nav for this on the UI @JamesHoover could you check out this thread? We are going to have /basics in the top level nav

**Comment by JamesHoover** [comment]
Bold are nav titles, slashes are the url. Whats the red mean?

**Comment by mkiser** [comment]
It was a change to either the root or structure of the URL

**Comment by StephanieKim** [comment]
Made the changes to add this under /basics and made /basics appear in nav
