### ISSUE TITLE
Customizing API Keys page is missing 

### ISSUE THREAD

**Issue by StephanieKim** [algorithmiaio/dev-center#69]
http://developers.algorithmia.com/basics/customizing-api-keys/ should be under https://test.algorithmia.com/developers/faqs/ 

I'm open to other places where it could go but going off what we decided in this doc: https://docs.google.com/document/d/10Wb81wvePhn_D7U1Gw5VSjxglygjYQeaqqWEuktE2hM/edit

**Comment by StephanieKim** [comment]
It's in the wrong spot and not linked to anywhere: /devcenter/basics/

**Comment by peckjon** [comment]
@StephanieKim do you mean that Cust API Keys page should be subnav to FAQ (assume not?), or that it should be listed in the FAQ?

What does that page belong under now... Algorithm Development maybe?

**Comment by StephanieKim** [comment]
Made the changes to add this under /basics and made /basics appear in nav
