### ISSUE TITLE
Home paragraph

### ISSUE THREAD

**Issue by doppenhe** [algorithmiaio/dev-center#76]
This seems like there should be some sort of intro. Right now the paragraph comes off as weird. Are we really starting with Hello World / algo development. 

![capture](https://cloud.githubusercontent.com/assets/2166701/22681123/7b684f3c-ecc0-11e6-90fe-01aecbc48b46.PNG)

**Comment by JamesHoover** [comment]
That is copy paste placeholder text

**Comment by StephanieKim** [comment]
I fixed this already closing
