### ISSUE TITLE
Footer should not be fixed.

### ISSUE THREAD

**Issue by besirkurtulmus** [algorithmiaio/dev-center#8]
![screen shot 2016-06-20 at 9 54 41 am](https://cloud.githubusercontent.com/assets/5170389/16202995/0bd60f64-36cd-11e6-8f2b-1c36f8cce70f.png)

**Comment by besirkurtulmus** [comment]
This currently happens on the [clients page.](http://developers.algorithmia.com/clients/)

**Comment by StephanieKim** [comment]
Not seeing this on new site - closing
