### ISSUE TITLE
Need to update the scikit-learn learn logo 

### ISSUE THREAD

**Issue by mkiser** [algorithmiaio/dev-center#9]
<img width="536" alt="screen shot 2016-06-30 at 12 39 44 pm" src="https://cloud.githubusercontent.com/assets/2197111/16501747/d2efcd66-3ebf-11e6-8ca9-e9dd30244393.png">

**Comment by doppenhe** [comment]
We can use generic model logo until we get the news onses.

https://drive.google.com/open?id=0B7WjkH-mZpoGMzl4QjZFWlZVUkE

**Comment by StephanieKim** [comment]
This is done in new site with new icons- closing
