### ISSUE TITLE
Overview nav element should not appear active when other pages are active.

### ISSUE THREAD

**Issue by JamesHoover** [algorithmiaio/dev-center#98]
![devcenter_issue_01](https://cloud.githubusercontent.com/assets/4503797/22842231/68f03aec-ef89-11e6-985b-e94729ffafee.png)

**Comment by StephanieKim** [comment]
@anowell if you want i can take a look if you point me where that code is

**Comment by anowell** [comment]
basically [this `is_ancestor` method](https://github.com/algorithmiaio/dev-center/blob/master/_plugins/navmenu.rb#L103-L113) isn't smart enough to realize that the overview link isn't a category ancestor even though it is a URL ancestor.... I had some ideas on how to fix it.. you're welcome to take a stab if you :heart: ruby.

**Comment by StephanieKim** [comment]
@anowell ha ha NM I thought it was just javascript lol

**Comment by peckjon** [comment]
@anowell please review https://github.com/algorithmiaio/dev-center/commit/f66b94bb0cb2800cf1b9cd3fc3cd2e673a49f02d for sanity?
